apiVersion: kapi.tapi.com/v1
kind: Kcrd
metadata:
  name: ktx
  namespace: "default"
spec:
  # Add fields here
  name: "ktx"
  finder: "kfnd"
  domain: "tasdid2.com"
  image: "tasdidur/test-ingress"
  port: 8002
  target-port: 8081
  paths:
    - "/hi"
    - "/hello"
    - "/bye"
status:
  all_ready: false
