# permissions for end users to view kcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcrd-viewer-role
rules:
- apiGroups:
  - kapi.tapi.com
  resources:
  - kcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapi.tapi.com
  resources:
  - kcrds/status
  verbs:
  - get
