
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kapi.tapi.com
  resources:
  - kcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapi.tapi.com
  resources:
  - kcrds/finalizers
  verbs:
  - update
- apiGroups:
  - kapi.tapi.com
  resources:
  - kcrds/status
  verbs:
  - get
  - patch
  - update
